spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/moqui?autoReconnect=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-server-instance1
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://my:1234@localhost:8080/eureka
logging:
  level: info