spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    name: myDataSource
    url: jdbc:mysql://127.0.0.1:3306/moqui?autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: org.apache.tomcat.jdbc.pool.DataSource
  second-datasource:
    url: jdbc:mysql://127.0.0.1:3306/cqliving_online?autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-client

server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://my:1234@localhost:8080/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.client.mybatis: debug
    root: info
turbine:
  instanceInsertPort: false
mybatis:
  config-location: classpath:mybatisConfig.xml
  mapper-locations: classpath*:mybatismapper/**/*.xml